import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/Components/Navigation/Navbar';
import Slidebar from "@/Components/Navigation/Slidebar";
import Footer from "@/Components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Appscrip",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
               
                <Slidebar/>
                <Navbar/>
                {children}
                <Footer/>
            </body>
        </html>
    );
}
