import { Inter } from "next/font/google";
import "./globals.css";
// import Nav from "@/components/navbar/Nav";
import Nav from '@/components/NavigationBar/Nav';
import Slide from "@/components/NavigationBar/slide";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "AppScrip",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
               
                <Slide/>
                <Nav/>
                {children}
                <Footer/>
            </body>
        </html>
    );
}
